"use client";

import { useThemeContext } from "@/context/ThemeContext";
import { Editor, OnMount } from "@monaco-editor/react";
import Box from "@mui/material/Box";
import { EditorSelection, RemoteCursor } from "@/lib/types/EditorSelection";
import { useEffect, useRef } from "react";
import type * as monaco from "monaco-editor";

type Props = {
  value: string;
  remoteCursors?: RemoteCursor[];
  onChange: (value: string | undefined) => void;
  onCursorChange?: (selection: EditorSelection) => void;
};

export default function CodeEditor({
  value,
  remoteCursors,
  onChange,
  onCursorChange,
}: Props) {
  const { themeName } = useThemeContext();

  // ==================== Refs

  const editorRef = useRef<monaco.editor.IStandaloneCodeEditor | null>(null);

  const monacoRef = useRef<typeof monaco | null>(null);

  const decorationsRef =
    useRef<monaco.editor.IEditorDecorationsCollection | null>(null);

  const onCursorChangeRef = useRef(onCursorChange);

  // True only while we are deliberately updating Monaco from React.
  const externalUpdateRef = useRef(false);

  // ==================== Cursor Callback

  useEffect(() => {
    onCursorChangeRef.current = onCursorChange;
  }, [onCursorChange]);

  // ==================== External Code Updates

  useEffect(() => {
    const editor = editorRef.current;

    if (!editor) return;

    const model = editor.getModel();

    if (!model) return;

    /*
     * If Monaco already has this value, this is just the parent
     * re-rendering after our own local edit.
     */
    if (model.getValue() === value) {
      return;
    }

    /*
     * The React value is different from Monaco.
     *
     * i.e. the change came from outside this editor:
     *
     * - remote user
     * - reset code
     * - changing problem
     */
    const currentSelection = editor.getSelection();

    externalUpdateRef.current = true;

    model.setValue(value);

    /*
     * setValue() moves the cursor.
     *
     * Restore the cursor/selection after the external update.
     */
    if (currentSelection) {
      const lineCount = model.getLineCount();

      const lineNumber = Math.min(
        currentSelection.positionLineNumber,
        lineCount,
      );

      const lineMaxColumn = model.getLineMaxColumn(lineNumber);

      const column = Math.min(currentSelection.positionColumn, lineMaxColumn);

      editor.setPosition({
        lineNumber,
        column,
      });
    }

    externalUpdateRef.current = false;
  }, [value]);

  // ==================== Editor Mount

  const handleEditorDidMount: OnMount = (editor, monaco) => {
    editorRef.current = editor;
    monacoRef.current = monaco;

    decorationsRef.current = editor.createDecorationsCollection();

    // ==================== Cursor / Selection

    editor.onDidChangeCursorSelection((event) => {
      /*
       * Do not emit cursor changes caused by our own external
       * model.setValue().
       */
      if (externalUpdateRef.current) return;

      const selection = event.selection;

      onCursorChangeRef.current?.({
        startLine: selection.startLineNumber,
        endLine: selection.endLineNumber,
        startColumn: selection.startColumn,
        endColumn: selection.endColumn,
        hasHighlight: !selection.isEmpty(),
      });
    });
  };

  // ==================== Code Change

  const handleChange = (newValue: string | undefined) => {
    /*
     * Ignore the onChange generated by model.setValue()
     * when React is updating Monaco externally.
     */
    if (externalUpdateRef.current) return;

    const newCode = newValue ?? "";

    /*
     * Monaco has already processed the edit at this point,
     * so getSelection() contains the cursor after typing.
     */
    const editor = editorRef.current;
    const selection = editor?.getSelection();

    onChange(newCode);

    if (selection) {
      onCursorChangeRef.current?.({
        startLine: selection.startLineNumber,
        endLine: selection.endLineNumber,
        startColumn: selection.startColumn,
        endColumn: selection.endColumn,
        hasHighlight: !selection.isEmpty(),
      });
    }
  };

  // ==================== Remote Cursor Colors

  const getColorIndex = (username: string) => {
    const usernames = [
      ...new Set(remoteCursors?.map((cursor) => cursor.username)),
    ];

    return usernames.indexOf(username);
  };

  // ==================== Remote Cursors

  useEffect(() => {
    const decorations = decorationsRef.current;
    const monaco = monacoRef.current;

    if (!decorations || !monaco || !remoteCursors) return;

    const newDecorations = remoteCursors.flatMap(({ username, selection }) => {
      const colorIndex = getColorIndex(username);

      const result = [];

      // ==================== Remote Selection

      if (selection.hasHighlight) {
        result.push({
          range: {
            startLineNumber: selection.startLine,
            startColumn: selection.startColumn,
            endLineNumber: selection.endLine,
            endColumn: selection.endColumn,
          },
          options: {
            className: `remote-selection-${colorIndex}`,
            stickiness:
              monaco.editor.TrackedRangeStickiness.GrowsOnlyWhenTypingBefore,
            hoverMessage: {
              value: `**${username}**`,
            },
          },
        });
      }

      // ==================== Remote Cursor

      const cursorColumn = selection.startColumn;

      result.push({
        range: {
          startLineNumber: selection.startLine,
          startColumn: cursorColumn,
          endLineNumber: selection.startLine,
          endColumn: cursorColumn + 1,
        },
        options: {
          className: `remote-cursor-${colorIndex}`,
          stickiness:
            monaco.editor.TrackedRangeStickiness.GrowsOnlyWhenTypingBefore,
          ...(!selection.hasHighlight && {
            hoverMessage: {
              value: `**${username}**`,
            },
          }),
        },
      });

      return result;
    });

    decorations.set(newDecorations);
  }, [remoteCursors]);

  // ==================== Render

  return (
    <Box sx={{ height: "100%", overflow: "hidden" }}>
      <Editor
        height="100%"
        defaultLanguage="python"
        language="python"
        theme={themeName === "light" ? "light" : "vs-dark"}
        defaultValue={value}
        onChange={handleChange}
        onMount={handleEditorDidMount}
        options={{
          fontSize: 14,
          fontFamily: "var(--font-code)",
          fontLigatures: false,

          minimap: {
            enabled: false,
          },

          automaticLayout: true,
          scrollBeyondLastLine: false,
          quickSuggestions: false,
          suggestOnTriggerCharacters: false,
          wordBasedSuggestions: "off",
          parameterHints: {
            enabled: false,
          },
        }}
      />
    </Box>
  );
}
